### PR TITLE
Adding French

### PR DESCRIPTION
**Pull request by rfrerebe**

### CODE REVIEW

**Comment by ploeh** [comment]
Is this the same as #8?

**Comment by rfrerebe** [comment]
Yes, with a fix for Zéro.

Rémy
Le mer. 10 févr. 2016 à 17:20, Mark Seemann <notifications@github.com> a
écrit :

**Comment by ploeh** [comment]
Would it make sense to reopen #8 and close this pull request, then?

Continuing work on #8 preserves the history of that pull request. Otherwise, this one essentially becomes a reboot.

**Comment by N0ct3** [comment]
Hello @ploeh 
I was seriously considering doing the french version when I saw this PR.
What is the status on it?

**Comment by ploeh** [comment]
@N0ct3, the overall status for the _Numsense_ project in general is that it's no longer active. It seems that no-one uses the library, and both contributors and reviewers have long since ceased activity.

I can definitely still go through the motions of merging a pull request and publishing a new version to NuGet, but as I don't speak French, I wouldn't be able to review any contribution like that.

Unless you're keen on doing the work in order to learn some F#, you're probably better off directing your energy towards something with a more promising future.

**Comment by N0ct3** [comment]
Thanks for the answer. I will follow you advice and focus on something else ;)

**Pull request closed without merging**
