### PR TITLE
Added Bulgarian

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to Numsense. This pull request looks promising :+1: 

When I run the build script, however, I get the following test failure:

```
    Ploeh.Numsense.NumeralProperties.negative Bulgarian is the inverse of positive Bulgarian [FAIL]
      FsCheck.Xunit.PropertyFailedException :
      Falsifiable, after 1 test (0 shrinks) (StdGen (1529042775,296111242)):
      Original:
      1

      ---- Swensen.Unquote.AssertionFailedException : Test failed:

      "minus ????" = "????? ????"
      false

      Stack Trace:

        ----- Inner Stack Trace -----
        Numsense.UnitTests\NumeralProperties.fs(19,0): at Ploeh.Numsense.NumeralProperties.negative Bulgarian is the inverse of positive Bulgarian@13.Invoke(Unit unitVar)
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.LazyInitValue()
           at FsCheck.Testable.Prop.safeForce[a](Lazy`1 body)
```

I suspect that the question marks (`????`) appear because my console (Git Bash) can't render the Bulgarian characters, but if I understand the failure, it's because the assertion expects `"minus"`, but gets something like `"минус"`.

**Comment by ncave** [comment]
Fixed, sorry about that.

**Comment by ploeh** [comment]
It builds and runs all tests without warnings on my machine, so from a technical perspective I think we're good to go :+1:

As I don't read Bulgarian, I'd like someone who does to review that part of it, if at all possible. I don't expect any errors, but it's always good with a second pair of eyes :smile:

**Comment by ploeh** [comment]
I solicited a review on Twitter: https://twitter.com/ploeh/status/693835670977118209

Please retweet and spread the word :smile:

**Comment by ncave** [comment]
Merged with upstream.

**Comment by ploeh** [comment]
I suppose we can consider no objections for 21 days as a passed review :smile: 

Thank you for your contribution! It's now live as [Numsense 0.10.0](https://www.nuget.org/packages/Numsense/0.10.0).

**Pull request merged**
