### PR TITLE
Added Polish implementation

### PR DESCRIPTION
**Pull request by kfazi**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to Numsense! It builds and runs all tests without warnings on my machine, so from a technical perspective I think we're good to go :+1: 

As I don't read Polish, I'd like someone who does to review that part of it, if at all possible. I don't expect any errors, but it's always good with a second pair of eyes :smile:

**Comment by ploeh** [comment]
I solicited a review on Twitter: https://twitter.com/ploeh/status/685910658156740609

Please retweet and spread the word :smile:

**Comment by ptrstpp950** [comment]
The polish text is correct but I am not an F# developer

**Comment by Krzysztof-Cieslak** [comment]
LGTM :+1:

**Comment by kfazi** [comment]
I've just removed some unused code.
This is just a cosmetic change which doesn't affect the translation.

**Comment by jkonecki** [comment]
Polish translation is fine

**Comment by ploeh** [comment]
Thank you, everyone, for your contribution! It's now live as [Numsense 0.2.0](https://www.nuget.org/packages/Numsense/0.2.0).

**Comment by ploeh** [comment]
No, it's not... Sorry, I messed up :flushed: 

Just a minute!

**Comment by ploeh** [comment]
OK, now it's live, as [Numsense 0.2.1](https://www.nuget.org/packages/Numsense/0.2.1)!

**Comment by ploeh** [comment]
@kfazi, when someone adds a new feature to one of the Open Source projects I run, I usually tweet a shout-out to that user. If you'd like me to do that, I'm going to need your Twitter handle.

This is completely optional.

**Comment by kfazi** [comment]
Thanks @ploeh!
My Twitter handle is `@kfazi` :smiley:

**Pull request merged**
