### PR TITLE
Added Romanian

### PR DESCRIPTION
**Pull request by bogdangaliceanu**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to Numsense! It builds and runs all tests without warnings on my machine, so from a technical perspective I think we're good to go :+1:

As I don't read Romanian, I'd like someone who does to review that part of it, if at all possible. I don't expect any errors, but it's always good with a second pair of eyes :smile:

**Comment by ploeh** [comment]
I solicited a review on Twitter: https://twitter.com/ploeh/status/697529858721718274

Please retweet and spread the word :smile:

**Comment by CosminLazar** [comment]
Reviewed the pull request and the Romanian part is okay

**Comment by ploeh** [comment]
Thank you for your contribution! It's now live as [Numsense 0.8.0](https://www.nuget.org/packages/Numsense/0.8.0).

**Pull request merged**
