### PR TITLE
Added Catalan language

### PR DESCRIPTION
**Pull request by mcliment**
Easier than Spanish!

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to Numsense! It builds and runs all tests without warnings on my machine, so from a technical perspective I think we're good to go :+1:

As I don't read Catalan, I'd like someone who does to review that part of it, if at all possible. I don't expect any errors, but it's always good with a second pair of eyes :smile:

**Comment by ploeh** [comment]
I solicited a review on Twitter: https://twitter.com/ploeh/status/693830914493804544

Please retweet and spread the word :smile:

**Comment by davidberneda** [comment]
Looks fine to me (cat: em sembla tot correcte)
http://www.languagesandnumbers.com/como-contar-en-catalan/es/cat/

What about adding billions, billiards, etc?

**Comment by ploeh** [comment]
> What about adding billions, billiards, etc?

It does handle `Int32.Max`, so that's as high as it goes.

Currently, [I don't think we need to support more than 32-bit integers](https://github.com/ploeh/Numsense/pull/12#issuecomment-172064136).

**Comment by vgaltes** [comment]
It looks good to me 👍 Bona feina!

**Comment by mcliment** [comment]
@davidberneda @ploeh I thought on adding _miliard_ which is an English _billion_ but I don't think it's a commonly used word. I'll add it when this PR is accepted.

**Comment by mcliment** [comment]
@ploeh This language has some similarities with the problems I encountered with Spanish and the spaces but in this case, hyphens can appear on some constructions. But the element solution proposed will apply to this case too.

**Comment by ploeh** [comment]
@mcliment How would you like to proceed with this pull request, then?

**Comment by mcliment** [comment]
To me it's done, feedback has been good. Just notice that in the Catalan case, hyphens/spaces are there for grammatical reasons.
If we move forward with the `ToLangElements` stuff I'll revisit this and add the feature.

**Comment by ploeh** [comment]
OK. As you may have noticed, the branch is no longer automatically mergeable. That's not your fault, but it's best when the author of a pull request gets a chance to address merge conflicts. Could you please do that?

Post here when done, so that I get a notification, and I'll pull :smile:

**Comment by mcliment** [comment]
Conflicts solved! :+1:

**Comment by ploeh** [comment]
Thank you, all, for your contributions! It's now live as [Numsense 0.5.0](https://www.nuget.org/packages/Numsense/0.5.0).

**Pull request merged**
