### PR TITLE
Italian language for Numsense

### PR DESCRIPTION
**Pull request by albertodall**
I implemented the Italian language support for Numsense.
All existing tests passed; I also added some new test cases to test some
"Italian cases". :-)

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to Numsense. This pull request touches 41 files. Could you please [narrow the focus](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests) of it?

**Comment by albertodall** [comment]
My apologies,
I think this happened because I committed the xunit.runner.visualstudio.2.1.0 package in the "packages" folder, and because, meanwhile, I merged once from origin.
Do I have to remove those commits?

**Comment by albertodall** [comment]
@ploeh I should have "narrowed the focus" of this pull request, as requested.

**Comment by ploeh** [comment]
Thank you. Please, however, take a look at the diff view. The pull request is still difficult to review due to files that look like they've been changed wholesale.

**Pull request closed without merging**
